config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifivations/index'
  root to: "homes#top"
  get "about" => "homes#about"

  devise_for :members, controllers: {
    registrations: "member/registrations",
    sessions: "member/sessions"
  }

  devise_scope :member do
    get "/members/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :companies, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :show, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :announcements
  end

  scope module: :member do
    get "search" => "searches#search"
    get "members/check" => "members#check"
    patch "members/withdraw" => "members#withdraw"
    resources :companies, except: [:destroy] do
      resources :comments, only: [:create, :new]
    end
    resources :comments, except: [:create, :new, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :members, only: [:show, :edit, :update]
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    resources :announcements
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  belongs_to :member
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :company, presence: true
  validates :company_kana, format: { with: /\p{katakana}/ }, presence: true
  validates :genre, presence: true
  validates :post_code, numericality: { only_integer: true }, format: { with: /\A\d{7}\z/ }, presence: true
  validates :address, presence: true
  validates :tel, numericality: { only_integer: true }, format: { with: /\A\d{10,11}\z/ }, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+.)+[a-z]{2,})\z/i }, presence: true

  enum genre: { 製造業: 0, 建設業: 1, 電気・ガス: 2,  運輸・通信業: 3, 卸売・小売業: 4, 飲食業: 5, 不動産業: 6, サービス業: 7, 金融・保険業: 8, 鉱業: 9, 農林: 10, 水産: 11 }

  def self.search_for(content, method)
    if method == "perfect"
      Company.where(company: content)
    elsif method == "forward"
      Company.where("company LIKE ?", content + "%")
    elsif method == "backward"
      Compnay.where("company LIKE ?", "%" + content)
    else
      Company.where("company LIKE ?", "%" + content + "%")
    end
  end
end

app/controllers/admin/companies_controller.rb
# frozen_string_literal: true

class Admin::CompaniesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @companies = Company.all.page(params[:page]).per(10)
  end

  def show
    if @company.nil?
      redirect_to admin_member_path
      flash[:notice] = "企業情報がまだ登録されていません。"
    else
      @company = Company.find(params[:id])
    end
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      flash[:notice] = "ステータス更新に成功しました"
      redirect_to admin_company_path(@company.id)
    else
      flash[:notice] = "ステータス更新に失敗しました"
      render :show
    end
  end

  private
    def company_params
      params.require(:company).permit(:is_active)
    end
end

app/controllers/member/companies_controller.rb
# frozen_string_literal: true

class Member::CompaniesController < ApplicationController
  before_action :authenticate_member!
  before_action :check_company_active, except: [:index, :new, :create]

  def new
    @company = Company.new
  end

  def create
    @company = current_member.build_company(company_params)
    @member = current_member
    @company.date_of_establishment = "〇年〇月"
    @company.introduction = "紹介文"
    if @company.save
      flash[:notice] = "企業の登録に成功しました。"
      redirect_to member_path(@member.id)
    else
      render :new
    end
  end

  def index
    @companies = Company.all.page(params[:page]).per(10)
    if current_member.company.nil?
    redirect_to new_company_path
    flash[:notice] = "企業情報がまだ登録されていません。このまま登録を行ってしてください。"
    end
  end

  def show
    @company = Company.find(params[:id])
    @comments = @company.comments.where(is_active: true)
    @member = @company.member
    @currentmemberEntry = Entry.where(member_id: current_member.id)
    @memberEntry = Entry.where(member_id: @member.id)
    if @member.id == current_member.id
      @msg = "他の企業の担当者とDMしてみよう！"
    else
      @currentmemberEntry.each do |cu|
        @memberEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      if @isRoom != true
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @company = Company.find(params[:id])
    @member = current_member
  end

  def update
    @company = Company.find(params[:id])
    @member = current_member
    if @company.update!(company_params)
      redirect_to member_path(@member.id)
    else
      render :edit
    end
  end

  def destroy
    member = current_member.find(params[:id])
    member.destroy
    redirect_to root_path
  end

  private
    def company_params
      params.require(:company).permit(:image, :company, :company_kana, :genre, :post_code, :address, :date_of_establishment, :introduction, :tel, :email, :member_id)
    end

    def check_company_active
      @company = Company.find(params[:id])
      unless @company.is_active
        redirect_to root_path
        flash[:notice] = "お探しの企業は解約済みです。"
      end
    end
end

app/helpers/admin/companies_helper.rb
# frozen_string_literal: true

module Admin::CompaniesHelper
end

app/helpers/member/companies_helper.rb
# frozen_string_literal: true

module Member::CompaniesHelper
end

app/views/admin/companies/index.html.erb
<div class="container py-5">
  <h2>企業一覧</h2>
  <div><%= flash[:notice] %></div>
  <div class="row">
    <table class="table table-borderbottom">
      <thead class="thead-info">
        <th style="width: 10%;">＜企業ID＞</th>
        <th style="width: 25%;">＜写真＞</th>
        <th style="width: 25%;">＜企業名＞</th>
        <th style="width: 15%;">＜業種＞</th>
        <th style="width: 15%;">＜ステータス＞</th>
      </thead>
      <% @companies.each do |company| %>
      <tbody>
        <td><%= company.id %></td>
        <td>
          <% if company.image.attached? %>
            <%= image_tag company.image, size: "150x150" %>
          <% else %>
            <%= image_tag 'company_free.jpg', size: "150x150" %>
          <% end %>
        </td>
        <td><%= link_to company.company, admin_company_path(company.id) %></td>
        <td><%= company.genre %></td>
        <td>
          <% if company.is_active %>
            表示
          <% else %>
            非表示
          <% end %>
        </td>
      </tbody>
      <% end %>
    </table>
    <div><%= paginate @companies %></div>
  </div>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}

.thead-info {
  background-color: #191970;
  color: white;
}

th, td {
  text-align: center;
  align-content: center;
}

.pagination {
  justify-content: center;
}
</style>

app/views/admin/companies/show.html.erb
<div class="container py-5">
  <h2>企業情報</h2>
  <div><%= flash[:notice] %></div>

  <table class="table table-borderd">
    <tr>
      <td style="width: 40%;"></td>
      <td style="width: 60%;">
        <% if @company.image.attached? %>
          <%= image_tag @company.image, size: "200x200" %>
        <% else %>
          <%= image_tag 'company_free.jpg', size: "200x200" %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>企業ID</th>
      <td><%= @company.id %></td>
    </tr>
    <tr>
      <th>企業名</th>
      <td><%= @company.company %></td>
    </tr>
    <tr>
      <th>企業名(カナ)</th>
      <td><%= @company.company_kana %></td>
    </tr>
    <tr>
      <th>業種</th>
      <td><%= @company.genre %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= @company.post_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @company.address %></td>
    </tr>
    <tr>
      <th>設立年月日</th>
      <td><%= @company.date_of_establishment %></td>
    </tr>
    <tr>
      <th>紹介</th>
      <td><%= @company.introduction %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @company.tel %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @company.email %></td>
    </tr>
    <tr>
      <th>投稿コメント</th>
      <td><%= button_to "コメントを見る", admin_comment_path, method: :get,  class: 'btn btn-primary' %></td>
    </tr>
    <tr>
      <th>ステータス</th>
      <td>
        <% if @company.is_active == true %>
          <%= form_with model: @company, url: admin_company_path(@company), method: :patch do |f| %>
            <%= f.hidden_field :is_active, value: false %>
            <%= f.submit "非表示に変更", class: "btn btn-sm btn-danger" %>
          <% end %>
        <% else %>
          <%= form_with model: @company, url: admin_company_path(@company), method: :patch do |f| %>
            <%= f.hidden_field :is_active, value: true %>
            <%= f.submit "表示に変更", class: "btn btn-sm btn-success" %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}
.thead-info th {
  background-color: #191970;
  color: white;
}

th {
  text-align: center;
  align-content: center;
}

td {
  text-align: start;
  align-content: center;
}

.pagination {
  justify-content: center;
}
</style>