config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifivations/index'
  root to: "homes#top"
  get "about" => "homes#about"

  devise_for :members, controllers: {
    registrations: "member/registrations",
    sessions: "member/sessions"
  }

  devise_scope :member do
    get "/members/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :companies, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :show, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :announcements
  end

  scope module: :member do
    get "search" => "searches#search"
    get "members/check" => "members#check"
    patch "members/withdraw" => "members#withdraw"
    resources :companies, except: [:destroy] do
      resources :comments, only: [:create, :new]
    end
    resources :comments, except: [:create, :new, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :members, only: [:show, :edit, :update]
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    resources :announcements
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
# frozen_string_literal: true

class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]

    case @model
    when "company"
      @records = Company.search_for(@content, @method).page(params[:page]).per(10)
    when "member"
      @records = Member.search_for(@content, @method).page(params[:page]).per(10)
    end
  end
end

app/controllers/member/searches_controller.rb
# frozen_string_literal: true

class Member::SearchesController < ApplicationController
  before_action :authenticate_member!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]

    case @model
    when "company"
      @records = Company.search_for(@content, @method).page(params[:page]).per(10)
    when "member"
      @records = Member.search_for(@content, @method).page(params[:page]).per(10)
    end
  end
end

app/helpers/admin/searches_helper.rb
# frozen_string_literal: true

module Admin::SearchesHelper
end

app/helpers/member/searches_helper.rb
# frozen_string_literal: true

module Member::SearchesHelper
end

app/views/admin/searches/_companies.html.erb
<div class="container py-3">
  <table class="table table-border">
    <tr>
      <th>企業名</th>
      <th>企業名カナ</th>
      <th>住所</th>
      <th></th>
    </tr>
    <% companies.each do |company| %>
      <% if company.is_active %>
        <tr>
          <td><%= company.company %></td>
          <td><%= company.company_kana %></td>
          <td><%= company.address %></td>
          <td><%= link_to "企業詳細へ", admin_company_path(company.id), class: "btn btn-success" %></td>
        </tr>
      <% end %>
    <% end %>
    </tr>
  </table>
  <div><%= paginate @records %></div>
</div>

<style>
  th {
    background-color: #191970;
    color: white;
    text-align: center;
    align-content: center;
  }

  td {
    text-align: center;
    align-content: center;
  }

  .pagination {
    justify-content: center;
  }
</style>

app/views/admin/searches/_members.html.erb
<div class="container py-3">
  <table class="table table-border">
    <tr>
      <th>会員名</th>
      <th>会員名カナ</th>
      <th>メールアドレス</th>
      <th></th>
    </tr>
    <% members.each do |member| %>
      <% if member.is_active %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.name_kana %></td>
        <td><%= member.email %></td>
        <td><%= link_to "会員詳細へ", admin_company_path(member.id), class: "btn btn-success" %></td>
      </tr>
      <% end %>
    <% end %>
  </table>
  <div><%= paginate members %></div>
</div>

<style>
  th {
    background-color: #191970;
    color: white;
    text-align: center;
    align-content: center;
  }

  td {
    text-align: center;
    align-content: center;
  }

  .pagination {
    justify-content: center;
  }
</style>

app/views/admin/searches/search.html.erb
<div class="container py-5">
  <% if @model == 'company' %>
    <h3>検索結果"<%= @content %>"</h3>
    <%= render 'admin/searches/companies', companies: @records %>
  <% elsif @model == 'member' %>
    <h3>検索結果"<%= @content %>" - 会員名</h3>
    <%= render 'admin/searches/members', members: @records %>
  <% end %>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}
</style>