config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifivations/index'
  root to: "homes#top"
  get "about" => "homes#about"

  devise_for :members, controllers: {
    registrations: "member/registrations",
    sessions: "member/sessions"
  }

  devise_scope :member do
    get "/members/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :companies, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :show, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :announcements
  end

  scope module: :member do
    get "search" => "searches#search"
    get "members/check" => "members#check"
    patch "members/withdraw" => "members#withdraw"
    resources :companies, except: [:destroy] do
      resources :comments, only: [:create, :new]
    end
    resources :comments, except: [:create, :new, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :members, only: [:show, :edit, :update]
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    resources :announcements
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
# frozen_string_literal: true

class Announcement < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
end

app/controllers/admin/announcements_controller.rb
# frozen_string_literal: true

class Admin::AnnouncementsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @announcements = Announcement.all.page(params[:page]).per(10)
  end

  def new
    @announcement = Announcement.new
  end

  def create
    @announcement = Announcement.new(announcement_params)
    @admin = current_admin
    @announcement.admin_id = @admin.id

    if @announcement.save
      flash[:notice] = "お知らせの登録に成功しました。"
      redirect_to admin_announcements_path
    else
      flash[:notice] = "お知らせの登録に失敗しました。"
      render :new
    end
  end

  def edit
    @announcement = Announcement.find(params[:id])
  end

  def update
    @announcement = Announcement.find(params[:id])

    if @announcement.update(announcement_params)
      flash[:notice] = "更新に成功しました。"
      redirect_to admin_announcements_path
    else
      flash[:notice] = "更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    announcement = Announcement.find(params[:id])
    announcement.destroy
    redirect_to admin_announcements_path
  end

  private
    def announcement_params
      params.require(:announcement).permit(:title, :body, :is_active)
    end
end

app/controllers/member/announcements_controller.rb
# frozen_string_literal: true

class Member::AnnouncementsController < ApplicationController
  def index
    @announcements = Announcement.all.page(params[:page]).per(10)
  end
end

app/views/admin/announcements/edit.html.erb
<div class="container py-5">
  <div class="row">
    <h2>お知らせ編集</h2>
  </div>
  <div><%= flash[:notice] %></div>

  <%= form_with model: @announcement, url: admin_announcement_path(@announcement.id), method: :patch do |f| %>
    <div class="row p-3 form-label">
      <div class="col-sm-2"><strong>件名</strong></div>
      <div class="col-md-8"><%= f.text_field :title, class: "form-control"%></div>
    </div>
    <div class="row p-3 form-label">
      <div class="col-sm-2"><strong>内容</strong></div>
      <div class="col-md-8"><%= f.text_area :body, class: "form-control", rows: "5" %></div>
    </div>
    <div class="row p-3 form-label">
      <div class="col-sm-2"><strong>公開/非公開</strong></div>
      <div class="col-md-8">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "公開", value: :true, class: 'active' %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "非公開", value: :false, class: 'inactive' %><br>
        <%= f.submit "更新", class:"btn btn-sm btn-success"%>
      </div>
    </div>
  <% end %>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}
</style>

app/views/admin/announcements/index.html.erb
<div class="container py-5">
  <h2>お知らせ管理</h2>
  <div class="text-right"><%= link_to "新規投稿", new_admin_announcement_path, class: "btn btn-primary" %></div>
  <p>お知らせ数：<%= @announcements.count %>件</p>
  <div><%= flash[:notice] %></div>

  <table class="table table-bordered">
    <thead class="thead-info">
      <tr>
        <th style="width: 70%;">[件名] 本文</th>
        <th class="position" style="width: 15%;">公開 / 非公開</th>
        <th class="position" style="width: 15%;">編集 / 削除</th>
      </tr>
    </thead>
    <% @announcements.each do |announcement| %>
    <tbody>
      <tr>
        <td class="md-6 text-position">
          [<strong><%= announcement.title %></strong>]<br>
          <%= announcement.body %><br>
        </td>
        <td class="position">
          <% if announcement.is_active == true %>
            <%= form_with model: announcement, url: admin_announcement_path(announcement), method: :patch do |f| %>
              <%= f.hidden_field :is_active, value: false %>
              <%= f.submit "非表示に変更", class: "btn btn-sm btn-secondary" %>
            <% end %>
          <% else %>
            <%= form_with model: announcement, url: admin_announcement_path(announcement), method: :patch do |f| %>
              <%= f.hidden_field :is_active, value: true %>
              <%= f.submit "表示に変更", class: "btn btn-sm btn-info" %>
            <% end %>
          <% end %>
        </td>
        <td class="position">
          <%= link_to "編集", edit_admin_announcement_path(announcement.id), class: "btn btn-success" %>
          <%= link_to "削除", admin_announcement_path(announcement.id), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
  <div><%= paginate @announcements %></div>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}

.thead-info {
  background-color: #FF8C00;
  color: white;
}

.text-position {
  text-align: start;
}

.position {
  text-align: center;
  align-content: center;
}

.pagination {
  justify-content: center;
}
</style>

app/views/admin/announcements/new.html.erb
<div class="container py-5">
  <div class="row">
    <h2>お知らせ登録</h2>
  </div>
  <div><%= flash[:notice] %></div>

  <%= form_with model: @announcement, url: admin_announcements_path do |f| %>
    <div class="row p-3 form-label">
      <div class="col-sm-2"><strong>件名</strong></div>
      <div class="col-md-5"><%= f.text_field :title, class: "form-control", style: "width:100%" %></div>
    </div>
    <div class="row p-3 form-label">
      <div class="col-sm-2"><strong>内容</strong></div>
      <div class="col-md-7"><%= f.text_area :body, class: "form-control", rows: "5" %></div>
    </div>
    <div class="row p-3 form-label">
      <div class="col-sm-2 title"><strong>公開/非公開</strong></div>
      <div class="col-md-5">
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "公開", value: :true, class: 'active' %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "非公開", value: :false, class: 'inactive' %><br>
        <%= f.submit "新規登録", class:"btn btn-sm btn-success"%>
      </div>
    </div>
  <% end %>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}
</style>