config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'notifivations/index'
  root to: "homes#top"
  get "about" => "homes#about"

  devise_for :members, controllers: {
    registrations: "member/registrations",
    sessions: "member/sessions"
  }

  devise_scope :member do
    get "/members/sign_out" => "devise/sessions#destroy"
  end

  devise_for :admins, controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :companies, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :show, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    resources :announcements
  end

  scope module: :member do
    get "search" => "searches#search"
    get "members/check" => "members#check"
    patch "members/withdraw" => "members#withdraw"
    resources :companies, except: [:destroy] do
      resources :comments, only: [:create, :new]
    end
    resources :comments, except: [:create, :new, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
    resources :members, only: [:show, :edit, :update]
    resources :messages, only: [:create, :destroy]
    resources :rooms, only: [:create, :show]
    resources :announcements
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/members_controller.rb
# frozen_string_literal: true

class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @member = Member.new
    @members = Member.all.page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      if @member.is_active?
        @member.company.update(is_active: true)
      else
        @member.company.update(is_active: false)
      end
      flash[:notice] = "会員ステータスを更新しました"
      redirect_to admin_members_path(@member)
    else

      flash[:notice] = "会員ステータスの更新に失敗しました"
      render :index
    end
  end

  private
    def member_params
      params.require(:member).permit(:is_active)
    end
end

app/controllers/member/announcements_controller.rb
# frozen_string_literal: true

class Member::AnnouncementsController < ApplicationController
  def index
    @announcements = Announcement.all.page(params[:page]).per(10)
  end
end

app/controllers/member/comments_controller.rb
# frozen_string_literal: true

class Member::CommentsController < ApplicationController
  before_action :authenticate_member!

  def index
    @company = current_member.company
    @comments = @company.comments.where(is_active: true).page(params[:page]).per(10)
  end

  def new
    @company = Company.find(params[:company_id]) if params[:company_id].present?
    @comment = Comment.new
  end

  def create
    @comment = current_member.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "コメント投稿に成功しました。"
      redirect_to company_path(@comment.company_id)
    else
      flash[:alert] = "コメント投稿に失敗しました。"
      @company = Company.find(params[:comment][:company_id])
      @comments = @company.comments.where(is_active: true).page(params[:page]).per(10)
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:comment, :company_id)
  end
end

app/controllers/member/companies_controller.rb
# frozen_string_literal: true

class Member::CompaniesController < ApplicationController
  before_action :authenticate_member!
  before_action :check_company_active, except: [:index, :new, :create]

  def new
    @company = Company.new
  end

  def create
    @company = current_member.build_company(company_params)
    @member = current_member
    @company.date_of_establishment = "〇年〇月"
    @company.introduction = "紹介文"
    if @company.save
      flash[:notice] = "企業の登録に成功しました。"
      redirect_to member_path(@member.id)
    else
      render :new
    end
  end

  def index
    @companies = Company.all.page(params[:page]).per(10)
    if current_member.company.nil?
    redirect_to new_company_path
    flash[:notice] = "企業情報がまだ登録されていません。このまま登録を行ってしてください。"
    end
  end

  def show
    @company = Company.find(params[:id])
    @comments = @company.comments.where(is_active: true)
    @member = @company.member
    @currentmemberEntry = Entry.where(member_id: current_member.id)
    @memberEntry = Entry.where(member_id: @member.id)
    if @member.id == current_member.id
      @msg = "他の企業の担当者とDMしてみよう！"
    else
      @currentmemberEntry.each do |cu|
        @memberEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end

      if @isRoom != true
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @company = Company.find(params[:id])
    @member = current_member
  end

  def update
    @company = Company.find(params[:id])
    @member = current_member
    if @company.update!(company_params)
      redirect_to member_path(@member.id)
    else
      render :edit
    end
  end

  def destroy
    member = current_member.find(params[:id])
    member.destroy
    redirect_to root_path
  end

  private
    def company_params
      params.require(:company).permit(:image, :company, :company_kana, :genre, :post_code, :address, :date_of_establishment, :introduction, :tel, :email, :member_id)
    end

    def check_company_active
      @company = Company.find(params[:id])
      unless @company.is_active
        redirect_to root_path
        flash[:notice] = "お探しの企業は解約済みです。"
      end
    end
end

app/controllers/member/confirmations_controller.rb
# frozen_string_literal: true

class Member::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/member/favorites_controller.rb
class Member::FavoritesController < ApplicationController
  before_action :authenticate_member!

  def create
    @comment = Comment.find(params[:comment_id])
    favorite = current_member.favorites.new(comment_id: @comment.id)
    if favorite.save
      @comment.create_notification_favorite!(current_member)
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    favorite = current_member.favorites.find_by(comment_id: @comment.id)
    favorite.destroy
  end
end

app/controllers/member/members_controller.rb
# frozen_string_literal: true

class Member::MembersController < ApplicationController
  before_action :authenticate_member!
  before_action :check_member_active, except: [:edit, :update]

  def show
    @member = Member.find(params[:id])
    @company = current_member.company
    if @company.nil?
    redirect_to new_company_path
    flash[:notice] = "企業情報がまだ登録されていません。このまま登録を行ってしてください。"
    end
  end

  def edit
    is_matching_login_member
    @member = Member.find(params[:id])
    @company = current_member.company
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to member_path(params[:id])
    else
      render :edit
    end
  end

  def withdraw
    @member = Member.find(current_member.id)
    @member.update(is_active: false)
    @member.company.update(is_active: false)
    reset_session
    redirect_to root_path
  end

  def destroy
    @member = Member.find(params[:id])
    @company = @member.company
    if @member.destroy
      @company.destroy if @company
      redirect_to root_path
    else
      render :edit
    end
  end

  private
    def is_matching_login_member
      member = Member.find(params[:id])
      unless member.id == current_member.id
        redirect_to member_path(current_member.id)
      end
    end

    def member_params
      params.require(:member).permit(:name, :name_kana, :email)
    end

    def is_active_changed_to_false?
      saved_change_to_attribute?(:is_active) && !is_active
    end

    def deactivate_company
      company.update(is_active: false) if company
    end

    def check_member_active
      @member = Member.find(params[:id])
      unless @member.is_active
        redirect_to root_path
        flash[:notice] = "お探しの会員は退会済みです。"
      end
    end
end

app/controllers/member/messages_controller.rb
# frozen_string_literal: true

class Member::MessagesController < ApplicationController
  before_action :authenticate_member!
  before_action :set_room, only: [:create, :destroy]

  def create
    if Entry.where(member_id: current_member.id, room_id: @room.id).present?
      @message = Message.new(message_params)
      if @message.save
        flash[:notice] = "送信しました。"
      else
        Rails.logger.error(@message.errors.full_messages.join(', '))
        flash[:notice] = "送信に失敗しました。"
      end
    end
    redirect_to room_path(@room.id)
  end

  def destroy
    message = Message.find(params[:message][:id])
    message.destroy
    redirect_to room_path(@room.id)
  end

  private
    def set_room
      @room = Room.find(params[:message][:room_id])
    end

    def message_params
      params.require(:message).permit(:member_id, :body, :room_id).merge(member_id: current_member.id)
    end
end

app/controllers/member/notifications_controller.rb
class Member::NotificationsController < ApplicationController
  before_action :authenticate_member!

  def index
    @notifications = current_member.passive_notifications.where(checked: false).includes(:visitor, :visited).order(created_at: :desc)
  end

  def mark_as_read
    notification = Notification.find(params[:id])
    notification.update(checked: true)
    redirect_to notifications_path, notice: '通知を既読にしました。'
  end
end

app/controllers/member/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Member::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/member/passwords_controller.rb
# frozen_string_literal: true

class Member::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/member/registrations_controller.rb
# frozen_string_literal: true

class Member::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   # @customer = Customer.new
  # end

  # # POST /resource
  # def create
  #   # @customer = Customer.new(create_users_params)
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
    def after_sign_in_path_for(resource)
      new_company_path
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :post_code, :address, :tel, :email, :is_active, :password_confirmation])
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/member/rooms_controller.rb
# frozen_string_literal: true

class Member::RoomsController < ApplicationController
  before_action :authenticate_member!

  def create
    @room = Room.create
    Entry.create(room_id: @room.id, member_id: current_member.id)
    Entry.create(params.require(:entry).permit(:member_id, :room_id).merge(room_id: @room.id))
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(member_id: current_member.id, room_id: @room.id).present?
      @messages = @room.messages.order(created_at: :desc)
      @message = Message.new
      @entries = @room.entries
    end
  end
end

app/controllers/member/searches_controller.rb
# frozen_string_literal: true

class Member::SearchesController < ApplicationController
  before_action :authenticate_member!

  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]

    case @model
    when "company"
      @records = Company.search_for(@content, @method).page(params[:page]).per(10)
    when "member"
      @records = Member.search_for(@content, @method).page(params[:page]).per(10)
    end
  end
end

app/controllers/member/sessions_controller.rb
# frozen_string_literal: true

class Member::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  before_action :member_state, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  private
    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
    end

    def member_state
      member = Member.find_by(email: params[:member][:email])
      return if member.nil?
      return unless member.valid_password?(params[:member][:password])
      member.update(is_active: true)
    end

  protected
    def after_sign_in_path_for(resource)
      root_path
    end

    def reject_member
      @member = Member.find_by(name: params[:member][:name])
      if @member
        if @member.valid_password?(params[:member][:password]) && (@member.is_active == false)
          flash[:notice] = "退会済みです。再度ご登録の上、ご利用ください。"
          redirect_to new_member_registration
        else
          flash[:notice] = "項目を入力してください"
        end
      end
    end
end

app/controllers/member/unlocks_controller.rb
# frozen_string_literal: true

class Member::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/member/comments_helper.rb
# frozen_string_literal: true

module Member::CommentsHelper
end

app/helpers/member/companies_helper.rb
# frozen_string_literal: true

module Member::CompaniesHelper
end

app/helpers/member/favorites_helper.rb
# frozen_string_literal: true

module Member::FavoritesHelper
end

app/views/member/members/check.html.erb
<div class="container py-5">
  <div class="text-center">
    <h1>本当に退会しますか？</h1>
  </div>

  <div class="text-center">
    <p>
      退会すると、会員登録情報や<br>
      これまでのコメントやDMが閲覧できなくなります。<br>
      また、企業登録情報も削除されます。<br>
      退会する場合は、「退会する」をクリックしてください。
    </p>
  </div>

  <div class="text-center">
    <%= link_to "退会しない", member_path(current_member.id), class: 'btn btn-primary' %>
    <%= link_to "退会する", members_withdraw_path, method: :patch, class: 'btn btn-danger', data: { confirm: "本当に退会しますか？" }  %>
  </div>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}
</style>

app/views/member/members/edit.html.erb
<div class="container py-5">
  <h3 class="bg">会員情報編集</h3>
  <% if @member.errors.any? %>
    <%= @member.errors.count %>件のエラーが発生しました
    <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model: @member, url: member_path(@member), method: :patch do |f| %>
    <div class="row py-2">
      <div class="col-md-2"><strong>名前</strong></div>
      <div class="col-offset-1"></div>
      <div class="col-md"><%= f.text_field :name, autofocus: true %></div>
    </div>
    <div class="row py-2">
      <div class="col-md-2"><strong>名前(カナ)</strong></div>
      <div class="col-offset-1"></div>
      <div class="col-md"><%= f.text_field :name_kana %></div>
    </div>
    <div class="row py-2">
      <div class="col-md-2"><strong>メールアドレス</strong></div>
      <div class="col-offset-1"></div>
      <div class="col-md"><%= f.email_field :email, style: "width:30%" %></div>
    </div>
    <div class="row py-2">
      <div class="col-md-2"></div>
      <div class="col-offset-1"></div>
      <div class="col-md">
      <%= f.submit "更新する", class: "btn btn-success" %>
      <%= link_to "退会画面へ", members_check_path, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}

</style>

app/views/member/members/show.html.erb
<div class="container py-5">
  <div class="row">
    <h2>マイページ</h2>
    <table class="table table-borderless">
      <thead class="thead-info">
        <th class="col-md-4"><strong>企業情報</strong></th>
        <th class="col-md-8"></th>
      </thead>
      <tbody class="tbody-info">
        <tr>
          <th class="col-md-4"><strong>企業写真</strong></th>
          <td class="col-md-8">
            <% if @company && @company.image.attached? %>
              <%= image_tag @company.image, size: "200x200" %>
            <% else %>
              <%= image_tag 'company_free.jpg', size: "200x200" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>企業名</strong></th>
          <td class="col-md-8"><%= @company.company %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>(カナ)</strong></th>
          <td class="col-md-8"><%= @company.company_kana %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>業種</strong></th>
          <td class="col-md-8"><%= @company.genre %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>郵便番号</strong></th>
          <td class="col-md-8"><%= @company.post_code %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>住所</strong></th>
          <td class="col-md-8"><%= @company.address %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>設立年</strong></th>
          <td class="col-md-8"><%= @company.date_of_establishment %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>紹介</strong></th>
          <td class="col-md-8"><%= @company.introduction %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>電話番号</strong></th>
          <td class="col-md-8"><%= @company.tel %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>メール</strong></th>
          <td class="col-md-8"><%= @company.email %></td>
        </tr>
        <tr>
          <td class="col-md-4"></td>
          <td class="box-action">
            <%= link_to "企業情報を編集", edit_company_path(@company.id), class: 'btn btn-warning' %>
            <%= link_to "コメントを見る", comments_path(@company.id), method: :get, class: 'btn btn-primary' %>
          </td>
        </tr>
      </tbody>
      <thead class="thead-info">
        <th class="col-md-4"><strong>会員情報</strong></th>
        <th class="col-md-8"></th>
      </thead>
      <tbody>
        <tr>
          <th class="col-md-4"><strong>名前</strong></th>
          <td class="col-md-8"><%= @member.name %></td>
        </tr>
        <tr>
          <th class="col-md-4"><strong>(カナ)</strong></th>
          <td class="col-md-8"><%= @member.name_kana %></td>
        </tr>
          <th class="col-md-4"><strong>メール</strong></th>
          <td class="col-md-8"><%= @member.email %></td>
        </tr>
        <tr>
          <td class="col-md-4"></td>
          <td class="box-action"><%= link_to "会員情報を編集", edit_member_path(@member.id), class: 'btn btn-warning' %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<style>
.container {
  font-family: "Noto Sans JP", sans-serif;
  font-optical-sizing: auto;
  font-weight: 400;
  font-style: normal;
}

.thead-info th {
  background-color: #191970;
  color: white;
}

th, td {
  text-align: start;
  align-content: center;
}

</style>